# Generated by Django 4.2.6 on 2023-10-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email_alter_customer_location_and_more'),
        ('shopcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='shopcard',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
