# Generated by Django 4.2.6 on 2023-10-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0002_alter_shopcard_owner_alter_shopcard_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
